apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peoplematchingbackend.fullname" . }}
  labels:
    {{- include "peoplematchingbackend.labels" . | nindent 4 }}
stringData:
{{ toYaml .Values.config | indent 2 }}
