{{- define "api.db_host" -}}
{{- if .Values.postgresql.enabled -}}
{{- printf "%s-%s" .Release.Name .Values.postgresql.nameOverride -}}
{{- else -}}
{{- .Values.postgresql.nameOverride -}}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
stringData:
{{ toYaml .Values.config | indent 2 }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.postgresqlUsername | default "postgres" }}:{{ .Values.postgresql.postgresqlPassword }}@{{ include "api.db_host" . }}/{{ .Values.postgresql.postgresqlDatabase }}"