apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-certs
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
{{ toYaml .Values.certs.b64 | indent 2 }}
stringData:
{{ toYaml .Values.certs.text | indent 2 }}