apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  minReadySeconds: {{ .Values.minReadySeconds | default 10 }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
        api/role: api
      {{- include "api.annotations" . | nindent 6 }}
    spec:
    {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
    {{- end }}
      volumes:
        - name: nginxconf
          configMap:
            name: {{ include "api.fullname" . }}-nginx
        - name: publicsite
          emptyDir: {}
        - name: bucketkey
          secret:
            secretName: {{ .Values.bucket_secret }}
        - name: apiconfig
          secret:
            secretName: {{ include "api.fullname" . }}
      initContainers:
        - name: api-init
          image: "{{ default (include "api.image" .) .Values.initImage }}"
          command: ["sh", "-c", "{{ .Values.api.initCommand }}"]
          volumeMounts:
            - name: publicsite
              mountPath: /var/www/nginx/public
          env:
            - name: SENTRY_DSN
              value: ""
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: DATABASE_URL
            - name: GOOGLE_CLOUD_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: GOOGLE_CLOUD_STORAGE_BUCKET
            - name: DATATRACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: DATATRACK_URL
            - name: DATATRACK_API_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: DATATRACK_API_URL
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.probe.enabled }}
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
            timeoutSeconds: {{ .Values.probe.timeout }}
            periodSeconds: {{ .Values.probe.period }}
            successThreshold: {{ .Values.probe.success }}
            failureThreshold: {{ .Values.probe.failure }}
            initialDelaySeconds: {{ .Values.probe.delay }}
          {{- end }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginxconf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: "nginx.conf"
            - name: publicsite
              mountPath: /var/www/public
        - name: api
          command: ["php-fpm", "-F"]
          image: "{{ include "api.image" . }}"
          imagePullPolicy: {{ .Values.pullPolicy | default "Always" }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: bucketkey
              mountPath: /var/www/key.json
              subPath: key.json
          envFrom:
          - secretRef:
              name: {{ include "api.fullname" . }}
      {{- if eq .Values.podAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "api.selectorLabels" . | nindent 20 }}
      {{- end }}
