apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-nginx
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/nginx.conf").AsConfig | indent 2 }}
