# Default values for connectclub-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/connect-club/connectclub-web
  pullPolicy: IfNotPresent
  tag: master-snapshot

imagePullSecret: "gitlab-registry"
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

config:
  API_PATH: http://api

ingress:
  # className: "nginx"
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: web.local

pdb:
  enabled: false
  minAvailable: 1

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 1

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
