# Default values for connectclub-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

config:
  API_PATH: http://api-stage

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: stage.connect.club

pdb:
  enabled: true

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
