apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datatrack.fullname" . }}-filebeat
  labels:
    {{- include "datatrack.labels" . | nindent 4 }}
data:
  filebeat.yml: |
    filebeat.config.modules:
      path: /usr/share/filebeat/modules.d/*.yml
      reload:
        enabled: false
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
      - /go/src/app/logs/json.log
      - /go/src/app/logs/json-*.log
      json.keys_under_root: true

    output.logstash:
      hosts: [{{ .Values.filebeat.logstashURI | quote }}]

    processors:
    - add_host_metadata:
        when.not.contains.tags: forwarded
    - add_cloud_metadata: ~
    - add_docker_metadata: ~
    - dns:
        type: reverse
        action: append
        fields:
          host.ip: agent.hostname
