apiVersion: v1
kind: Service
metadata:
  name: {{ include "datatrack.fullname" . }}
  labels:
    {{- include "datatrack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8083
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "datatrack.selectorLabels" . | nindent 4 }}
