apiVersion: v1
kind: Service
metadata:
  name: {{ include "datatrack.fullname" . }}-headless
  labels:
    {{- include "datatrack.labels" . | nindent 4 }}
spec:
  clusterIP: None
  # type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "datatrack.selectorLabels" . | nindent 4 }}
